import 'dart:ui';
import 'package:flutter/material.dart';
import '../../core/app_export.dart';

/// Helper class for managing themes and colors.
class ThemeHelper {
  // The current app theme
  var _appTheme = PrefUtils().getThemeData();

// A map of custom color themes supported by the app
  Map<String, PrimaryColors> _supportedCustomColor = {
    'primary': PrimaryColors()
  };

// A map of color schemes supported by the app
  Map<String, ColorScheme> _supportedColorScheme = {
    'primary': ColorSchemes.primaryColorScheme
  };

  /// Changes the app theme to [_newTheme].
  void changeTheme(String _newTheme) {
    PrefUtils().setThemeData(_newTheme);
    Get.forceAppUpdate();
  }

  /// Returns the primary colors for the current theme.
  PrimaryColors _getThemeColors() {
    //throw exception to notify given theme is not found or not generated by the generator
    if (!_supportedCustomColor.containsKey(_appTheme)) {
      throw Exception(
          "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");
    }
    //return theme from map

    return _supportedCustomColor[_appTheme] ?? PrimaryColors();
  }

  /// Returns the current theme data.
  ThemeData _getThemeData() {
    //throw exception to notify given theme is not found or not generated by the generator
    if (!_supportedColorScheme.containsKey(_appTheme)) {
      throw Exception(
          "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");
    }
    //return theme from map

    var colorScheme =
        _supportedColorScheme[_appTheme] ?? ColorSchemes.primaryColorScheme;
    return ThemeData(
      colorScheme: colorScheme,
      elevatedButtonTheme: ElevatedButtonThemeData(
        style: ElevatedButton.styleFrom(
          backgroundColor: appTheme.black900,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(
              4,
            ),
          ),
        ),
      ),
      outlinedButtonTheme: OutlinedButtonThemeData(
        style: OutlinedButton.styleFrom(
          backgroundColor: Color(0XFFFFFFFF),
          shape: RoundedRectangleBorder(
            side: BorderSide(
              color: colorScheme.primary,
              width: 1,
            ),
            borderRadius: BorderRadius.circular(
              16,
            ),
          ),
        ),
      ),
      textTheme: TextTheme(
        bodyMedium: TextStyle(
          color: Colors.black,
          fontSize: getFontSize(
            14,
          ),
          fontFamily: 'Rubik',
          fontWeight: FontWeight.w400,
        ),
        bodySmall: TextStyle(
          color: appTheme.gray900,
          fontSize: getFontSize(
            12,
          ),
          fontFamily: 'Rubik',
          fontWeight: FontWeight.w400,
        ),
        titleMedium: TextStyle(
          color: appTheme.black900,
          fontSize: getFontSize(
            16,
          ),
          fontFamily: 'Rubik',
          fontWeight: FontWeight.w600,
        ),
        bodyLarge: TextStyle(
          color: appTheme.gray50001,
          fontSize: getFontSize(
            16,
          ),
          fontFamily: 'Rubik',
          fontWeight: FontWeight.w400,
        ),
        titleSmall: TextStyle(
          color: appTheme.gray400,
          fontSize: getFontSize(
            14,
          ),
          fontFamily: 'Rubik',
          fontWeight: FontWeight.w600,
        ),
        titleLarge: TextStyle(
          color: appTheme.black900,
          fontSize: getFontSize(
            20,
          ),
          fontFamily: 'Rubik',
          fontWeight: FontWeight.w400,
        ),
        headlineSmall: TextStyle(
          color: appTheme.gray900,
          fontSize: getFontSize(
            24,
          ),
          fontFamily: 'Rubik',
          fontWeight: FontWeight.w400,
        ),
      ),
      visualDensity: VisualDensity.standard,
    );
  }

  /// Returns the primary colors for the current theme.
  PrimaryColors themeColor() => _getThemeColors();

  /// Returns the current theme data.
  ThemeData themeData() => _getThemeData();
}

/// Class containing the supported color schemes.
class ColorSchemes {
  static final primaryColorScheme = ColorScheme.light(
    background: Color(0XFFFEFFFF),
    error: Color(0XFFFFFFFF),
    errorContainer: Color(0XFFEC1B55),
    inversePrimary: Color(0XFFFEFFFF),
    inverseSurface: Color(0XFFFFFFFF),
    onBackground: Color(0XFF323232),
    onError: Color(0XFF323232),
    onErrorContainer: Color(0XFFFFFFFF),
    onInverseSurface: Color(0XFF323232),
    onPrimary: Color(0XFFFFFFFF),
    onPrimaryContainer: Color(0XFF323232),
    onSecondary: Color(0XFF323232),
    onSecondaryContainer: Color(0XFFFFFFFF),
    onSurface: Color(0XFF323232),
    onSurfaceVariant: Color(0XFFFFFFFF),
    onTertiary: Color(0XFF323232),
    onTertiaryContainer: Color(0XFFFFFFFF),
    outline: Color(0XFFFFFFFF),
    outlineVariant: Color(0XFFFEFFFF),
    primary: Color(0XFFEC1B55),
    primaryContainer: Color(0XFFFEFFFF),
    scrim: Color(0XFFFEFFFF),
    secondary: Color(0XFFFEFFFF),
    secondaryContainer: Color(0XFFEC1B55),
    shadow: Color(0XFFFFFFFF),
    surface: Color(0XFFFEFFFF),
    surfaceTint: Color(0XFFFFFFFF),
    surfaceVariant: Color(0XFFEC1B55),
    tertiary: Color(0XFFFEFFFF),
    tertiaryContainer: Color(0XFFEC1B55),
  );
}

/// Class containing custom colors for a primary theme.
class PrimaryColors {
  // Black
  Color get black900 => Color(0XFF000000);
  // BlueGray
  Color get blueGray400 => Color(0XFF888888);
  Color get blueGray900 => Color(0XFF072F35);
  // Gray
  Color get gray300 => Color(0XFFE2E2EA);
  Color get gray400 => Color(0XFFB4B4BE);
  Color get gray500 => Color(0XFF9E9EA2);
  Color get gray50001 => Color(0XFF9D9D9D);
  Color get gray600 => Color(0XFF686873);
  Color get gray900 => Color(0XFF171625);
  // Pink
  Color get pink700 => Color(0XFFD40A42);
  // Red
  Color get red900 => Color(0XFFA70000);
  // Yellow
  Color get yellow70023 => Color(0X23FEBD2F);
}

PrimaryColors get appTheme => ThemeHelper().themeColor();
ThemeData get theme => ThemeHelper().themeData();
